# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 639d5cac4b47098eef50f8fa2fed6e7c0938e2451cc1c0eabed56eb1713fb8b1b186ddb72b287f6c30d32b9a889e64f3382f49e4d6a9bd4b1c6cff335f2bf5f6

test:
  secret_key_base: e4863ed166162d40858f71cfa8ee2e19ed4ecb97f7554ec3b2ac224f20c9e566ea9b79a33ebf543fb9f40b9e6a5d7170d4b2d5e1d618ec52d76aa43d2ffb4031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
